### ISSUE TITLE
how to use the webpixel  for other usecase

### ISSUE THREAD

**Issue by adventuretocode** [benzookapi/shopify-barebone-app-sample#2]
@benzookapi   thanks for the working and sharing the knowledge of the web pixel.

I am building the web pixel app extension can be run the gtm script code like third party js code in the app pixel.

how to migrate script_tag or theme app extension to the webpixel ?

can I write any js code in the js files ?

what are limitation for web pixel ?

Facebook pixel can be work with app pixel ?

**Comment by benzookapi** [comment]
Hi, app pixels runs as WebWorker which cannot touch DOM and sample is for app pixels only. 

If you want to use GTM, you should use custom pixel which needs written manually in the admin settings. 
https://help.shopify.com/en/manual/promoting-marketing/pixels/custom-pixels

Facebook, X, and TikTok, other script based tracking as well.

You can provide those tags as theme  app extensions but which is only for outside Checkout as Liquid templates, if you want to get data during the checkout and use JS tag directly,  the only way should be using custom pixel manual insertion.

However, if you have other APIs which can be accessed via fetch() over CORS  as GA4 API I use for this sample, it works fine.  I think some Open APIs with simple HTTP header authentication should exist but I don't have any quick names in mind...

**Comment by adventuretocode** [comment]
@benzookapi  thank you so much... I don't want to access the DOM.  I just want to run the third part script 


`import { register } from "@shopify/web-pixels-extension";

register(({ configuration, analytics, browser, settings, init }) => {
 // Initialize GTM tag
 (function (w, d, s, l, i) {
 w[l] = w[l] || [];
 w[l].push({ 'gtm.start': new Date().getTime(), event: 'gtm.js' });
 var f = d.getElementsByTagName(s)[0], j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : '';
 j.async = true;
 j.src = 'https://www.googletagmanager.com/gtm.js?id=' + i + dl;
 f.parentNode.insertBefore(j, f);
 })(window, document, 'script', 'dataLayer', 'GTM-5GKJCS3D');

 analytics.subscribe('all_events', event => {
 // Subscribe to all events
 });

 analytics.subscribe('all_standard_events', event => {
 // Subscribe to all standard events
 });

 // Other GTM-related code and event tracking can go here
});`

**Comment by benzookapi** [comment]
If you want to write those code, you can't use web pixels, unfortunately.... 

Instead, you can do in custom pixels. (See my link above).

You can test it out in Shopify admin,  settings > customer event.

**Comment by adventuretocode** [comment]
> >
Custom pixel i get but I want to do with the app pixel.. 

runtime_context = "strict"
#runtime_context = "lax"
can Use the lax for the app pixel ??

**Comment by benzookapi** [comment]
This page should answer your question with detailed limitation....
https://shopify.dev/docs/apps/marketing/pixels

app (web) pixel = strict 
custom pixel = lax

These are fixed by Shopify, we can't control within the code...
